# Generated by Django 4.1.1 on 2022-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('cantHuesos', models.IntegerField()),
                ('fechaNac', models.DateField()),
            ],
        ),
    ]
